Rian
esteh-creative/rumahpekerja-tailwindcss pull request #14
Opened 2022-07-30 06:35 UTC by Rian-P

Belum merapihkan slide

2022-07-30 07:15 UTC, alfangr commented on index.html
> +    <nav class="bg-white  shadow-sm   ">
hapus spasi yang tidak di perlukan

2022-07-30 07:16 UTC, alfangr commented on index.html
> +    </style>
ubah posisi tag style di bawah tag title

2022-07-30 07:17 UTC, alfangr commented on index.html
> +            <div class="hidden pl-10  md:block md:w-10/12  ">
urutkan classnya sesuai value cssnya, harusnya hidden md:block pl-10 ..., agar mudah dibaca

2022-07-30 07:18 UTC, alfangr commented on index.html
> +                    <li class="py-4 px-2 ">
hapus spasi yang tidak perlu

2022-07-30 07:19 UTC, alfangr commented on index.html
> +                            class=" text-gray-700 font-semibold py-4 px-2  rounded inline-flex items-center hover:text-red-500">
text-gray-700 hover:text-red-500 ..., urutkan jadi seperti ini agar mudah di baca

2022-07-30 07:42 UTC, alfangr commented on index.html
> +                            <span class="mr-1 text-[16px] ">Lainnyaaa</span>
Lainnyaaa ke Lainnya, dulu ini typo dari aku mintol di fixkan juga ya

2022-07-30 07:43 UTC, alfangr commented on index.html
> +                    class=" md:flex items-center inline-block relative flex flex-wrap md:flex-row md:space-x-2  md:text-sm md:font-medium pl-64 ">
md:flex di hapus saja, karean duplikasi

2022-07-30 07:44 UTC, alfangr commented on index.html
> +                    <a href=""
href kosong bisa di kasih hashtag

2022-07-30 07:45 UTC, alfangr commented on index.html
> +                            class="bg-transparent text-[16px]  hover:bg-[#F2404D]  text-black font-semibold hover:text-white py-2 px-4 border border-[#F2404D] hover:border-transparent rounded-lg">
tag button di tambahkan attribute type="button"

2022-07-30 07:46 UTC, alfangr commented on index.html
> +
hapus baris yang tidak perlu

2022-07-30 07:47 UTC, alfangr commented on index.html
> +    <div class=" bg-gray-100 container rounded-xl mt-6 mb-10 md:max-w-5xl block mr-[170px] ml-[170px]">
mr-[170px] ml-[170px] bisa di ubah ke mx-[170px]

2022-07-30 07:48 UTC, alfangr commented on index.html
> +            <div class="  w-1/2 p-4 mr-2 rounded-3xl p-14">
p-4 dan p-14 duplikasi, pilih salah satu

2022-07-30 07:53 UTC, alfangr commented on index.html
> +                            class="bg-background border border-white-300 text-black-900 text-sm rounded-lg focus:ring-blue-500  block w-full pl-10 p-2.5  dark:bg-background-700 dark:border-white-600
`pl-10 p-2.5`, ini bentrok di plnya bisa diubah ke `pl-10 pr-2.5 py-2.5`

2022-07-30 07:54 UTC, alfangr commented on index.html
> +                            class="bg-background border border-white-300 text-black-900 text-sm rounded-lg focus:ring-blue-500  block w-full pl-10 p-2.5  dark:bg-background-700 dark:border-white-600
`dark:` ini sepertinya tidak digunakan semisal memang ngga digunakan bisa di hapus saja

2022-07-30 07:54 UTC, alfangr commented on index.html
> +
hapus baris yang tidak perlu

2022-07-30 07:57 UTC, alfangr commented on index.html
> +    <div class="   rounded-xl p-4 bg-primary    mr-[170px] ml-[170px]  ">
`mr-[170px] ml-[170px]` ganti ke `mx-[170px]`

2022-07-30 07:58 UTC, alfangr commented on index.html
> +
hapus baris yang tidak perlu

2022-07-30 07:58 UTC, alfangr commented on index.html
> +            <div class="   mb-2 rounded-lg  ">
hapus komen yang tidak perlu

2022-07-30 07:59 UTC, alfangr commented on index.html
> +                    <button
tambah type="button"

2022-07-30 07:59 UTC, alfangr commented on index.html
> +        <button type="button" class="py-2 px-4 pl-64">
hapus komen

2022-07-30 08:00 UTC, alfangr commented on index.html
> +        <div class="border bg-pink     pl-28 mb-10 mt-10 w-full   ">
`mb-10 mt-10` ganti ke `my-10`

2022-07-30 08:01 UTC, alfangr commented on latihanslide.html
> +   -->
hapus typo

2022-07-30 08:01 UTC, alfangr requested changes
ada beberapa komen yang perlu perubahan

2022-08-01 13:00 UTC, alfangr commented on index.html
>                      <p class="text-sm text-[14px] text-gray-600 flex items-center">
text-sm sama text-[14px] ini dpulcate, harus milih salah satu

2022-08-01 13:01 UTC, alfangr commented on index.html
> +                        class="p-2.5 ml-2 text-sm font-medium text-white bg-red-700 rounded-lg border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-60
fungsi dark: bisa di hapus saja

2022-08-01 13:50 UTC, alfangr commented on index.html
>          <button
Tambahkan attribute type=“button”

2022-08-01 13:51 UTC, alfangr requested changes
Perubahan minor

2022-08-18 12:22 UTC, alfangr approved these changes
bisa di merge ya

2022-08-18 14:14 UTC, Rian-P commented
belum resposnsive slide

2022-08-18 14:24 UTC, alfangr commented
ganti PR ke merge

2022-08-18 14:24 UTC, closed without merging